# Header

menu:
  主页: /
  相册: "#"
  全部文章: /archives/
# SubNav
subnav:
  github: "https://github.com/desnbo"
  weibo: "http://weibo.com/u/3517404784"
  jianshu: "http://www.jianshu.com"
  rss: "atom.xml"
  #zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #douban: "#"
  #mail: "mailto:desnbo@q163.com"
  #mail: "#"
  #facebook: "#"
  #google: "#"  
  #twitter: "#"
  #linkedin: "#"

# 标签云
tagcloud: true

rss: /atom.xml


# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

fancybox: true #开启fancybox效果

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
# 打赏wording
reward_wording: 'Just for fun~'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: 
# 微信二维码图片地址
weixin: 

# Miscellaneous
baidu_analytics: 'cfb838bc0cdbeea6622ed505429ab9a9'
google_analytics: false
favicon: /assets/img/favicon.png

#你的头像url
avatar: /assets/img/avatar.png

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 5. gitment 
#不需要使用某项，直接设置值为false，或注释掉

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色或图片
  #1. 是否统一设置: 若否,注释或设为false
  #header: '#263238'
  header:  false
  # 宽屏时颜色或图片url(300*180)
  headerbg: 'url(/assets/img/headerbg.png) center top no-repeat'
  # 窄屏时颜色或图片url(800*140)
  headerbg_m: 'url(/assets/img/headerbg_m.png) center top no-repeat'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 文章目录toc
# 如果配置为true, 在文章前添加 toc: false 单篇文章不生成目录
# 如果配置为false,在文章前添加 toc: true  单篇文章生成目录
#toc: true | false
toc: false

## pace loading 加载特效 
pace: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '标签'
  #friends: '友邻'
  friends: false
  aboutme: 'ME'

friends:
  错过的时光: "#"
  遗失的美好: "#"
 

aboutme: Make it Happen,<br><br> Make is Simple!<br>
